# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetID' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetID

pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'GoogleSignIn'


  target 'PetIDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PetIDUITests' do
    # Pods for testing
  end

end
